/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

import {
  ClassicSigninErrorResponse,
  ClassicSigninRequest,
  ClassicSigninResponse,
  LogoutResponse,
} from "./auth.types";
import { ContentType, HttpClient, RequestParams } from "../http-client";

export class AuthApi<
  SecurityDataType = unknown,
> extends HttpClient<SecurityDataType> {
  /**
 * @description Authenticate a user with email and password via VTEX ID
 *
 * @tags auth
 * @name ClassicSignin
 * @request POST:/api/v1/auth/classic-signin
 * @response `200` `ClassicSigninResponse` Default Response
 * @response `400` `{
  /** @example false *\/
    success?: boolean,
    data?: null | object,
    error?: {
  /** @example "AUTH_INVALID_EMAIL" *\/
    code?: string,
  /** @example "Invalid email address" *\/
    message?: string,

},
    meta?: {
    requestId?: string,
    timestamp?: string,

},

}` Missing or invalid request fields
 * @response `401` `({
  /** @example false *\/
    success?: boolean,
    data?: object | null,
    error?: {
  /** @example "AUTH_INVALID_CREDENTIALS" *\/
    code?: string,
  /** @example "Invalid email or password" *\/
    message?: string,

},
    meta?: {
    requestId?: string,
    timestamp?: string,

},

} | {
  /** @example false *\/
    success?: boolean,
    data?: object | null,
    error?: {
  /** @example "AUTH_ERROR" *\/
    code?: string,
  /** @example "Authentication failed" *\/
    message?: string,

},
    meta?: {
    requestId?: string,
    timestamp?: string,

},

})` Unauthorized responses
 * @response `403` `{
  /** @example false *\/
    success?: boolean,
    data?: null,
    error?: {
  /** @example "AUTH_ACCOUNT_LOCKED" *\/
    code?: string,
  /** @example "Account is blocked" *\/
    message?: string,

},
    meta?: {
    requestId?: string,
    timestamp?: string,

},

}` Account is blocked or usage limits exceeded
 */
  classicSignin = (data: ClassicSigninRequest, params: RequestParams = {}) =>
    this.request<ClassicSigninResponse, ClassicSigninErrorResponse>({
      path: `/api/v1/auth/classic-signin`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description Log out the current user and clear VTEX ID session cookies
   *
   * @tags auth
   * @name Logout
   * @request GET:/api/v1/auth/logout
   * @response `204` `LogoutResponse` Default Response
   */
  logout = (params: RequestParams = {}) =>
    this.request<LogoutResponse, any>({
      path: `/api/v1/auth/logout`,
      method: "GET",
      ...params,
    });
}
