/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

export interface SigninData {
  authStatus?: string;
}

export interface ClassicSigninRequest {
  username: string;
  password: string;
}

export interface ClassicSigninResponse {
  success?: boolean;
  data?: SigninData;
  error?: null | object;
  meta?: {
    requestId?: string;
    timestamp?: string;
  };
}

/**
 * Missing or invalid request fields
 * Account is blocked or usage limits exceeded
 */
export type ClassicSigninErrorResponse =
  | {
      /** @example false */
      success?: boolean;
      data?: null | object;
      error?: {
        /** @example "AUTH_INVALID_EMAIL" */
        code?: string;
        /** @example "Invalid email address" */
        message?: string;
      };
      meta?: {
        requestId?: string;
        timestamp?: string;
      };
    }
  | (
      | {
          /** @example false */
          success?: boolean;
          data?: object | null;
          error?: {
            /** @example "AUTH_INVALID_CREDENTIALS" */
            code?: string;
            /** @example "Invalid email or password" */
            message?: string;
          };
          meta?: {
            requestId?: string;
            timestamp?: string;
          };
        }
      | {
          /** @example false */
          success?: boolean;
          data?: object | null;
          error?: {
            /** @example "AUTH_ERROR" */
            code?: string;
            /** @example "Authentication failed" */
            message?: string;
          };
          meta?: {
            requestId?: string;
            timestamp?: string;
          };
        }
    )
  | {
      /** @example false */
      success?: boolean;
      data?: null;
      error?: {
        /** @example "AUTH_ACCOUNT_LOCKED" */
        code?: string;
        /** @example "Account is blocked" */
        message?: string;
      };
      meta?: {
        requestId?: string;
        timestamp?: string;
      };
    };

export type LogoutResponse = any;
