/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

import {
  GetProductDetailsParams,
  GetProductDetailsResponse,
} from "./product.types";
import { HttpClient, RequestParams } from "../http-client";

export class ProductApi<
  SecurityDataType = unknown,
> extends HttpClient<SecurityDataType> {
  /**
   * @description Get product details with variations and SKU context
   *
   * @tags product
   * @name GetProductDetails
   * @request GET:/api/v1/product/{productId}
   * @response `200` `GetProductDetailsResponse` Default Response
   */
  getProductDetails = (
    { productId }: GetProductDetailsParams,
    params: RequestParams = {},
  ) =>
    this.request<GetProductDetailsResponse, any>({
      path: `/api/v1/product/${productId}`,
      method: "GET",
      format: "json",
      ...params,
    });
}
