/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

export interface ProductDetailsData {
  product?: Record<string, any>;
  variations?: Record<string, any>;
  [key: string]: any;
}

export interface GetProductDetailsParams {
  /** @pattern ^[0-9]+$ */
  productId: string;
}

export interface GetProductDetailsResponse {
  success?: boolean;
  data?: ProductDetailsData;
  error?: null | object;
  meta?: {
    requestId?: string;
    timestamp?: string;
    [key: string]: any;
  };
  [key: string]: any;
}
