/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

export enum HealthStatus {
  Ok = "ok",
  Degraded = "degraded",
  Down = "down",
}

export interface HealthData {
  status?: HealthStatus;
  uptime?: number;
  env?: string;
  timestamp?: string;
  version?: string;
}

export interface HealthCheckResponse {
  success?: boolean;
  data?: HealthData;
  error?: null | object;
  meta?: {
    requestId?: string;
    timestamp?: string;
  };
}
