/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

import { HealthCheckResponse } from "./health.types";
import { HttpClient, RequestParams } from "../http-client";

export class HealthApi<
  SecurityDataType = unknown,
> extends HttpClient<SecurityDataType> {
  /**
   * @description Health check endpoint
   *
   * @tags health
   * @name HealthCheck
   * @request GET:/health
   * @response `200` `HealthCheckResponse` Default Response
   */
  healthCheck = (params: RequestParams = {}) =>
    this.request<HealthCheckResponse, any>({
      path: `/health`,
      method: "GET",
      format: "json",
      ...params,
    });
}
