import * as fs from "node:fs";
import * as path from "node:path";
import * as dotenv from "dotenv";
import { generateApi, type GenerateApiParams } from "swagger-typescript-api";

dotenv.config({ path: ".env.local" });

const SOURCE = process.env.OPENAPI_SOURCE ?? "local";
const URL = process.env.BFF_OPENAPI_URL ?? "http://localhost:3001/documentation/json";
const OUT = path.resolve(process.cwd(), "api-specs-model");
const LOCAL_PATH = path.resolve(process.cwd(), "openapi.json");
const SKIP = new Set(["api", "v1", "v2", "v3"]);

type Schemas = Record<string, unknown>;
type Spec = { paths?: Record<string, unknown>; components?: { schemas?: Schemas } };
type SpecLiteral = Extract<GenerateApiParams, { spec: unknown }>["spec"];

// Collect component schema names reachable from a node, following $refs transitively.
function collectRefs(node: unknown, schemas: Schemas, acc: Set<string>) {
  if (!node || typeof node !== "object") return;
  if (Array.isArray(node)) {
    for (const item of node) collectRefs(item, schemas, acc);
    return;
  }
  for (const [key, value] of Object.entries(node)) {
    const ref =
      key === "$ref" && typeof value === "string" && value.match(/\/components\/schemas\/(.+)$/);
    if (ref && !acc.has(ref[1])) {
      acc.add(ref[1]);
      collectRefs(schemas[ref[1]], schemas, acc);
    } else {
      collectRefs(value, schemas, acc);
    }
  }
}

function pascal(s: string) {
  return s
    .split(/[-_]/)
    .filter(Boolean)
    .map((x) => x.charAt(0).toUpperCase() + x.slice(1))
    .join("");
}

function domainOf(pathStr: string) {
  return (
    pathStr
      .replace(/^\//, "")
      .split("/")
      .find((s) => !SKIP.has(s) && !s.startsWith("{")) ?? "misc"
  );
}

// Banner for generated files: skips linting and signals the file is not hand-edited.
const HEADER =
  "/* eslint-disable */\n// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.\n\n";

function writeGenerated(filePath: string, content: string) {
  fs.writeFileSync(filePath, HEADER + content);
}

async function main() {
  if (SOURCE !== "local") {
    const res = await fetch(URL);
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    fs.writeFileSync(LOCAL_PATH, JSON.stringify(await res.json(), null, 2));
  }

  const spec = JSON.parse(fs.readFileSync(LOCAL_PATH, "utf-8")) as Spec;

  const domains = new Map<string, Record<string, unknown>>();
  for (const [pathStr, item] of Object.entries(spec.paths ?? {})) {
    const domain = domainOf(pathStr);
    if (!domains.has(domain)) domains.set(domain, {});
    domains.get(domain)![pathStr] = item;
  }

  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const allSchemas = spec.components?.schemas ?? {};

  let httpClientWritten = false;
  for (const [domain, paths] of domains) {
    const used = new Set<string>();
    collectRefs(paths, allSchemas, used);
    const schemas = Object.fromEntries([...used].map((name) => [name, allSchemas[name]]));

    const { files } = await generateApi({
      spec: { ...spec, paths, components: { ...spec.components, schemas } } as SpecLiteral,
      output: false,
      modular: true,
      httpClientType: "fetch",
      generateClient: true,
      generateResponses: true,
      enumStyle: "enum",
      extractEnums: true,
      extractRequestParams: true,
      extractRequestBody: true,
      extractResponseBody: true,
      extractResponseError: true,
      extractingOptions: {
        requestBodySuffix: ["Request", "Payload", "Body", "Input"],
        responseBodySuffix: ["Response", "Data", "Result", "Output"],
        responseErrorSuffix: ["ErrorResponse", "Error", "Fail", "Fault"],
      },
    });

    const contentOf = (name: string) => files.find((f) => f.fileName === name)?.fileContent ?? "";
    const route = files.find(
      (f) => f.fileName !== "data-contracts" && f.fileName !== "http-client",
    );
    const dir = path.join(OUT, domain);
    fs.mkdirSync(dir, { recursive: true });

    writeGenerated(path.join(dir, `${domain}.types.ts`), contentOf("data-contracts"));

    const api = (route?.fileContent ?? "")
      .replace('from "./data-contracts"', `from "./${domain}.types"`)
      .replace('from "./http-client"', 'from "../http-client"')
      .replace(/export class \w+</, `export class ${pascal(domain)}Api<`);
    writeGenerated(path.join(dir, `${domain}.api.ts`), api);

    if (!httpClientWritten) {
      writeGenerated(path.join(OUT, "http-client.ts"), contentOf("http-client"));
      httpClientWritten = true;
    }
  }

  const exports = ['export * from "./http-client";'];
  for (const domain of domains.keys()) {
    exports.push(`export * from "./${domain}/${domain}.types";`);
    exports.push(`export * from "./${domain}/${domain}.api";`);
  }
  writeGenerated(path.join(OUT, "index.ts"), `${exports.join("\n")}\n`);

  console.log(`✓ ${domains.size} domains: ${[...domains.keys()].join(", ")}`);
}

main().catch(() => process.exit(1));
