/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

export interface Cart {
  itemCount?: number;
  cartId?: string;
  locale?: string;
  items?: CartItem[];
}

export interface CartItem {
  id?: string;
  seller?: string;
  quantity?: number;
  price?: number;
}

export interface GetCartResponse {
  success?: boolean;
  data?: Cart;
  error?: null | object;
  meta?: {
    requestId?: string;
    timestamp?: string;
  };
}

/** @minItems 1 */
export type AddCartItemsRequest = {
  skuId: string;
  sellerId: string;
  /** @min 1 */
  quantity: number;
}[];

export interface AddCartItemsResponse {
  success?: boolean;
  data?: Cart;
  error?: null | object;
  meta?: {
    requestId?: string;
    timestamp?: string;
  };
}
