/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit manually.

import {
  AddCartItemsRequest,
  AddCartItemsResponse,
  GetCartResponse,
} from "./checkout.types";
import { ContentType, HttpClient, RequestParams } from "../http-client";

export class CheckoutApi<
  SecurityDataType = unknown,
> extends HttpClient<SecurityDataType> {
  /**
   * @description Retrieve the current user's cart
   *
   * @tags cart
   * @name GetCart
   * @request GET:/api/v1/checkout/cart
   * @response `200` `GetCartResponse` Default Response
   */
  getCart = (params: RequestParams = {}) =>
    this.request<GetCartResponse, any>({
      path: `/api/v1/checkout/cart`,
      method: "GET",
      format: "json",
      ...params,
    });
  /**
   * @description Add one or more items to the current user's cart
   *
   * @tags cart
   * @name AddCartItems
   * @request POST:/api/v1/checkout/cart/add-items
   * @response `200` `AddCartItemsResponse` Default Response
   */
  addCartItems = (data: AddCartItemsRequest, params: RequestParams = {}) =>
    this.request<AddCartItemsResponse, any>({
      path: `/api/v1/checkout/cart/add-items`,
      method: "POST",
      body: data,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
}
